# Generated by Django 4.0.2 on 2022-02-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_ichki_bolim'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='mamlakat',
            field=models.CharField(default="O'zbekiston", max_length=30),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='ichki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='mainapp.ichki'),
        ),
    ]
