# Generated by Django 4.0.2 on 2022-02-28 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=35)),
                ('rasm', models.FileField(blank=True, upload_to='mijoz')),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=30)),
                ('jins', models.CharField(max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shahar', models.CharField(max_length=25)),
                ('davlat', models.CharField(max_length=35)),
                ('kocha', models.CharField(max_length=40)),
                ('uy', models.CharField(max_length=40)),
                ('zipcode', models.PositiveIntegerField()),
                ('mijoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.mijoz')),
            ],
        ),
    ]
