# Generated by Django 4.0.2 on 2022-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_manzil_kocha_alter_mijoz_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manzil',
            name='uy',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='manzil',
            name='zipcode',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
