# Generated by Django 4.0.2 on 2022-02-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_manzil_uy_alter_manzil_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manzil',
            name='zipcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
