# Generated by Django 4.0.2 on 2022-03-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_mijoz_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mijoz',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
